### ISSUE TITLE
Email with files

### ISSUE THREAD

**Issue by larod241** [drpioneer/MikrotikBackup#1]
Amazing work. Thanks a lot.

Is it possible to add email send with file of the backup when it's done ? 

Regards

**Comment by drpioneer** [comment]
Hello!
My plans do not include the addition of sending an email with a backup file.

**Comment by larod241** [comment]
Hello, Ok, thanks for this answer and too bad for me. 
I'll try to cobble something in parallel.
Regards

**Comment by drpioneer** [comment]
If you have a desire - share your best practices
