### ISSUE TITLE
Сохранять бекапы в папку и чистить тоже только ее содержимое.

### ISSUE THREAD

**Issue by Voljka1** [drpioneer/MikrotikBackup#2]
Приветствую. Нельзя ли чуть доработать скрипт, чтобы всунуть в него:
1) бекап конфигурации самого роутера (уже есть)
2) бекап базы данных Dude (нету)
3) настройку фолдера на диске, куда пишутся бекапы и в котором должны удаляться старые файлы. (нету)

У меня роутер с nvme1 диском, на котором работает Dude. Хотелось бы бекапить его базу туда же, в папку nvme1/backups.
Спасибо.

**Comment by drpioneer** [comment]
Приветствую!

п.1 работает.
п.3 тоже работает, просто это не очевидно, нужно ЗАРАНЕЕ создать папку.
Например, создаёте папку в Windows и перетаскиваете её куда надо в Winbox, в окно Files.
Затем в настройках скрипта отключаете автоматическое определение накопителя и прописываете полный путь к папке через символ "/".
Касаемо п.2 - с Dude никогда дела не имел. Опишите как нужно действовать?

**Comment by Voljka1** [comment]
бекап дюда делается двумя командами:
:local dudeconffilename "Dude_configuration_backup"
:local dudedbfilename "Dude_db_backup"
:local dudeconffileext "rsc"
:local dudedbfileext "db"
/dude export file="$localbackuppath/$dudeconffilename_$now.$dudeconffileext"
/dude export-db backup-file="$localbackuppath/$dudedbfilename_$now.$dudedbfileext"

Я наверное многого прошу, но может быть найдете время и желание немного упростить свой скрипт для текущей версии ROS7, где:
- дата в стандартном виде time: 19:07:22 ,date: 2024-11-02 ?
- путь к диску и папка указываются в явном виде переменными (одной или раздельными)?
Такой облегченный вариант исходного скрипта? Спасибо.

**Comment by drpioneer** [comment]
В чём смысл Вашего пожелания?

Пока у меня имеется зоопарк из устройств с разными версиями ROS6 и 7, стремлюсь писать код, единообразно работающий в обоих версиях ROS. Плодить разные версии кода под разные запросы сильного желания нет.

**Comment by drpioneer** [comment]
Дополнил код на предмет бэкапа базы и конфигурации Dude. Предлагаю Вам проверить работоспособность и отписать о результатах.

**Comment by Voljka1** [comment]
![image](https://github.com/user-attachments/assets/f8928619-e95b-4609-bf79-acd6c396ec3b)
Если бы меня кто спросил, то я бы предпочел видеть имена в виде DUDE_2024-11-15.xxx, DUDE_2024-11-15_dude.xxx
И еще, если бекапить чаще, чем раз в сутки, то имеем перезаписывание, так как время не добавляется к имени.
В результате хорошо бы иметь имя типа: RouterID_YYYY-MM-DD_HH-MM.xxx, RouterID_YYYY-MM-DD_HH-MM_dude.xxx 
И уже как бы просится делать отдельный каталог для каждого бекапа с именем как YYYY-MM-DD_HH-MM.
Вот как-то так, спасибо.

**Comment by Voljka1** [comment]
И еще про Dude. Место его установки описывается в конфиге как:
/dude
set data-directory=sd1/dude enabled=yes

Если подумать о бекапе не только его базы данных, но и файлов, которые пользователь добавил к его стандартной конфигурации, то напрашивается архивация файлов и каталогов по пути "sd1/dude/files", при этом сохранять путь "sd1/dude/files/default" не требуется, т.к. это read-only каталог и создается при установке dude.
Т,е. пользователь дополняет Dude файлами по путям:
sd1/dude/files/[mibs, images, fonts, packages]

**Comment by drpioneer** [comment]
1. Касаемо предпочитаемого формата имен файлов, в 95й строке замените названия месяцев на: "-01-","-02-" и т.д. Должно сработать.
2. При бекапе чаще, чем раз в сутки, разве каждый последующий бекап не содержит в себе все предыдущие наработки? Какой смысл бекапить чаще, чем раз в сутки?
3. Что подразумевается под **архивацией** файлов и каталогов, добавленных пользователем?

**Comment by Voljka1** [comment]
2. Кроме резервной копии есть еще версионирование. Если бекап был в час ночи, днем сделали изменения, затерли ночную копию, а вечером решили откатиться назад, то откатываться некуда. Как мне кажется, перед любыми изменениями хорошо иметь резервную копию на которую можно откатиться без размышлений...
3. Архивация - оно же копирование. Хотя если весь скрипт выполнять по планировщику, то каждый раз сохранять все файлы Dude уже не выглядит хорошей идеей. Забудем про файлы Dude, их можно вручную скопировать в безопасное место. P.S. У меня не раз было, что мои файлы пропадали из рабочего пути при перезагрузке или оновлении Dude.

**Comment by drpioneer** [comment]
- 1й пункт сделал.
 - 2й пункт сделал.
 - 3й пункт забываем.
Проверяйте работу скрипта. Отпишите о результате.

**Comment by Voljka1** [comment]
Скрипт работает, файлы создаются, старые файлы удаляются. Я добавил только подчеркивание в имена, чтобы было ххх22-45_dude.ххх

**Comment by drpioneer** [comment]
Считаю задачу выполненной, поэтому закрываю её.
Пользуетесь скриптом - отметьте это звёздочкой. Мне будет приятно. Заранее спасибо.
